// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8Zyn2PO5xj0cKwpYhCHZ8bHnwDdVIGg',
    appId: '1:620239726314:web:cbe03661c808c0e0ab1993',
    messagingSenderId: '620239726314',
    projectId: 'gpit-c806f',
    authDomain: 'gpit-c806f.firebaseapp.com',
    storageBucket: 'gpit-c806f.firebasestorage.app',
    measurementId: 'G-M7V0BD9L69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedm9J_gc4HhLkACSeB7Qqfi_aXdBwltQ',
    appId: '1:620239726314:android:f8cb99a48d1f5360ab1993',
    messagingSenderId: '620239726314',
    projectId: 'gpit-c806f',
    storageBucket: 'gpit-c806f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZny_-B7PdTZ_YnBIkBOt0R8u9e0fE3Fk',
    appId: '1:620239726314:ios:1a7a825c45e9c354ab1993',
    messagingSenderId: '620239726314',
    projectId: 'gpit-c806f',
    storageBucket: 'gpit-c806f.firebasestorage.app',
    iosBundleId: 'com.example.aabuProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZny_-B7PdTZ_YnBIkBOt0R8u9e0fE3Fk',
    appId: '1:620239726314:ios:1a7a825c45e9c354ab1993',
    messagingSenderId: '620239726314',
    projectId: 'gpit-c806f',
    storageBucket: 'gpit-c806f.firebasestorage.app',
    iosBundleId: 'com.example.aabuProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8Zyn2PO5xj0cKwpYhCHZ8bHnwDdVIGg',
    appId: '1:620239726314:web:42a579a2063771c7ab1993',
    messagingSenderId: '620239726314',
    projectId: 'gpit-c806f',
    authDomain: 'gpit-c806f.firebaseapp.com',
    storageBucket: 'gpit-c806f.firebasestorage.app',
    measurementId: 'G-RKZDMDEHXD',
  );
}
